version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/packages/qf-pipeline"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/qti-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/qf-scaffolding"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
